// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djozrzgevluayzcvenby.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqb3pyemdldmx1YXl6Y3ZlbmJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NzE1OTYsImV4cCI6MjA2NTE0NzU5Nn0.fYF44Xt8D0VWTEITw9TR_6MhdLHJdctM7DA-wen7w8k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});